basePath: /
definitions:
  dto.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handlers.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: msaorc@hotmail.com
    name: Marcos Augusto
    url: http://M&ASistem.com.br
  description: API for controlling day-to-day expenses.
  license:
    name: M&ASistem
    url: http://M&ASistem.com.br
  termsOfService: http://swagger.io/terms/
  title: ExpenseControl API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Create User
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
